dist: xenial

language: python
python:
  - "3.8.2"

services:
  - docker

env:
  - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - pipenv check
  - pipenv run inv qa
  - pipenv run coveralls

deploy:
  - provider: script
    script: >-
      pipenv run inv docker-deploy
      --username "$DOCKER_USERNAME"
      --password "$DOCKER_PASSWORD"
      --repository "mailer"
      --tag "$TRAVIS_TAG"
    on:
      tags: true

  - provider: script
    script: >-
      pipenv run inv docker-deploy
      --username "$DOCKER_USERNAME"
      --password "$DOCKER_PASSWORD"
      --repository "mailer"
      --tag "latest"
    on:
      tags: false
      all_branches: true

  - provider: script
    script: >-
      npm install -g now &&
      pipenv run inv now-deploy
      --now-token "$NOW_TOKEN"
      --now-project "$NOW_PROJECT"
      --now-target "production"
      --now-alias "$NOW_ALIAS"
    on:
      tags: true

  - provider: script
    script: >-
      npm install -g now &&
      pipenv run inv now-deploy
      --now-token "$NOW_TOKEN"
      --now-project "$NOW_PROJECT"
      --now-target "staging"
    on:
      tags: false
      all_branches: true
