dist: xenial

language: python
python:
    - "3.7"

services:
  - docker

install:
  - pip install pipenv coveralls
  - pipenv install --dev

script:
  - pipenv run inv qa
  - pipenv run coveralls

deploy:
  - provider: script
    script: pipenv run inv docker_deploy -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" -r "mailer" -t "$TRAVIS_TAG"
    on:
      tags: true
  - provider: script
    script: pipenv run inv docker_deploy -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" -r "mailer" -t "latest"
