dist: xenial

language: python
python:
  - "3.7"

services:
  - docker

env:
  - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - pipenv check
  - pipenv run inv qa
  - pipenv run coveralls

deploy:
  - provider: script
    script: pipenv run inv docker-deploy -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" -r "mailer" -t "$TRAVIS_TAG"
    on:
      tags: true
  - provider: script
    script: pipenv run inv docker-deploy -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" -r "mailer" -t "latest"
    on:
      tags: false
      all_branches: true
